# -*- coding: utf-8 -*-
"""Streamlit 3 - Antoine BLANCHÉ.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t8hGCMM7amoCH6GmyrifsycW84ebZ1K0
"""

import streamlit as st
from streamlit_authenticator import Authenticate
from streamlit_option_menu import option_menu

lesDonneesDesComptes = {
    'usernames': {
        'utilisateur': {
            'name': 'utilisateur',
            'password': 'utilisateurMDP',
            'email': 'utilisateur@gmail.com',
            'failed_login_attemps': 0,
            'logged_in': False,
            'role': 'utilisateur'
        },
        'root': {
            'name': 'root',
            'password': 'rootMDP',
            'email': 'admin@gmail.com',
            'failed_login_attemps': 0,
            'logged_in': False,
            'role': 'administrateur'
        }
    }
}

authenticator = Authenticate(
    lesDonneesDesComptes,
    "cookie name",
    "cookie key",
    30,
)

authenticator.login()

def accueil():
    st.title("Bienvenue sur le contenu réservé aux utilisateurs connectés")

if st.session_state.get("authentication_status"):
    accueil()

    authenticator.logout("Déconnexion")

    with st.sidebar:  # Tentative de sidebar, inspirée du roi Giulio
        selection = option_menu(
            menu_title="Navigation",
            options=["Accueil", "Photos"],
            icons=["house", "camera"],
            menu_icon="cast",
            default_index=0
        )

    if selection == "Accueil":
        st.write("Bienvenue sur la page d'accueil !")
    elif selection == "Photos":
        st.write("Bienvenue sur mon album photo !")